'use strict';window.DOMHandler=class{constructor(b,e){this._iRuntime=b;this._componentId=e;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(b,e,h,l){this._iRuntime.PostToRuntimeComponent(this._componentId,b,e,h,l)}PostToRuntimeAsync(b,e,h,l){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,b,e,h,l)}_PostToRuntimeMaybeSync(b,e,h){this._iRuntime.UsesWorker()?this.PostToRuntime(b,e,h):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:b,dispatchOpts:h||null,data:e,responseId:null})}AddRuntimeMessageHandler(b,e){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,b,e)}AddRuntimeMessageHandlers(b){for(const [e,h]of b)this.AddRuntimeMessageHandler(e,h)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(b,e){this._callback=b;this._interval=e;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(b){this._canRunImmediate=!!b}Call(){if(-1===this._timerId){var b=Date.now(),e=b-this._lastCallTime,h=this._interval;e>=h&&this._canRunImmediate?(this._lastCallTime=b,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(h-e,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(b,e){super(b,e);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",h=>this._OnCreate(h)],["destroy",h=>this._OnDestroy(h)],["set-visible",h=>this._OnSetVisible(h)],["update-position",h=>this._OnUpdatePosition(h)],["update-state",h=>this._OnUpdateState(h)],["focus",h=>this._OnSetFocus(h)],["set-css-style",h=>this._OnSetCssStyle(h)],["set-attribute",h=>this._OnSetAttribute(h)],["remove-attribute",
h=>this._OnRemoveAttribute(h)]]);this.AddDOMElementMessageHandler("get-element",h=>h)}SetAutoAttach(b){this._autoAttach=!!b}AddDOMElementMessageHandler(b,e){this.AddRuntimeMessageHandler(b,h=>{const l=this._elementMap.get(h.elementId);return e(l,h)})}_OnCreate(b){const e=b.elementId,h=this.CreateElement(e,b);this._elementMap.set(e,h);h.style.boxSizing="border-box";b.isVisible||(h.style.display="none");b=this._GetFocusElement(h);b.addEventListener("focus",l=>this._OnFocus(e));b.addEventListener("blur",
l=>this._OnBlur(e));this._autoAttach&&document.body.appendChild(h)}CreateElement(b,e){throw Error("required override");}DestroyElement(b){}_OnDestroy(b){b=b.elementId;const e=this._elementMap.get(b);this.DestroyElement(e);this._autoAttach&&e.parentElement.removeChild(e);this._elementMap.delete(b)}PostToRuntimeElement(b,e,h){h||(h={});h.elementId=e;this.PostToRuntime(b,h)}_PostToRuntimeElementMaybeSync(b,e,h){h||(h={});h.elementId=e;this._PostToRuntimeMaybeSync(b,h)}_OnSetVisible(b){this._autoAttach&&
(this._elementMap.get(b.elementId).style.display=b.isVisible?"":"none")}_OnUpdatePosition(b){if(this._autoAttach){var e=this._elementMap.get(b.elementId);e.style.left=b.left+"px";e.style.top=b.top+"px";e.style.width=b.width+"px";e.style.height=b.height+"px";b=b.fontSize;null!==b&&(e.style.fontSize=b+"em")}}_OnUpdateState(b){const e=this._elementMap.get(b.elementId);this.UpdateState(e,b)}UpdateState(b,e){throw Error("required override");}_GetFocusElement(b){return b}_OnFocus(b){this.PostToRuntimeElement("elem-focused",
b)}_OnBlur(b){this.PostToRuntimeElement("elem-blurred",b)}_OnSetFocus(b){const e=this._GetFocusElement(this._elementMap.get(b.elementId));b.focus?e.focus():e.blur()}_OnSetCssStyle(b){this._elementMap.get(b.elementId).style[b.prop]=b.val}_OnSetAttribute(b){this._elementMap.get(b.elementId).setAttribute(b.name,b.val)}_OnRemoveAttribute(b){this._elementMap.get(b.elementId).removeAttribute(b.name)}GetElementById(b){return this._elementMap.get(b)}};"use strict";
{const b=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),e=/android/i.test(navigator.userAgent);let h=0;function l(d){const a=document.createElement("script");a.async=!1;a.type="module";return d.isStringSrc?new Promise(f=>{const g="c3_resolve_"+h;++h;self[g]=f;a.textContent=d.str+`\n\nself["${g}"]();`;document.head.appendChild(a)}):new Promise((f,g)=>{a.onload=f;a.onerror=g;a.src=d;document.head.appendChild(a)})}let n=!1,r=!1;function v(){if(!n){try{new Worker("blob://",{get type(){r=
!0}})}catch(d){}n=!0}return r}let w=new Audio;const x={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;async function H(d){d=await E(d);return(new TextDecoder("utf-8")).decode(d)}
function E(d){return new Promise((a,f)=>{const g=new FileReader;g.onload=k=>a(k.target.result);g.onerror=k=>f(k);g.readAsArrayBuffer(d)})}const y=[];let z=0;window.RealFile=window.File;const A=[],D=new Map,u=new Map;let F=0;const B=[];self.runOnStartup=function(d){if("function"!==typeof d)throw Error("runOnStartup called without a function");B.push(d)};const I=new Set(["cordova","playable-ad","instant-games"]);function G(d){return I.has(d)}let c=!1;window.RuntimeInterface=class d{constructor(a){this._useWorker=
a.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._workerScriptURLs={};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;this._isFileProtocol="file"===location.protocol.substr(0,4);!this._useWorker||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&v()||(this._useWorker=
!1);if("playable-ad"===this._exportType||"instant-games"===this._exportType)this._useWorker=!1;if("cordova"===this._exportType&&this._useWorker)if(e){const f=/Chrome\/(\d+)/i.exec(navigator.userAgent);f&&90<=parseInt(f[1],10)||(this._useWorker=!1)}else this._useWorker=!1;this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||!this._isFileProtocol||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
"html5"!==this._exportType||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",f=>this._OnCordovaFetchLocalFile(f));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",f=>this._OnCreateJobWorker(f));"cordova"===this._exportType?document.addEventListener("deviceready",
()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}IsFileProtocol(){return this._isFileProtocol}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return b&&
"cordova"===this._exportType}IsiOSWebView(){const a=navigator.userAgent;return b&&G(this._exportType)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}IsAndroid(){return e}IsAndroidWebView(){return e&&G(this._exportType)}async _Init(a){"macos-wkwebview"===this._exportType&&this._SendWrapperMessage({type:"ready"});if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let g=0,k=a.engineScripts.length;g<
k;++g){var f=a.engineScripts[g].toLowerCase();this._localFileStrings.hasOwnProperty(f)?a.engineScripts[g]={isStringSrc:!0,str:this._localFileStrings[f]}:this._localFileBlobs.hasOwnProperty(f)&&(a.engineScripts[g]=URL.createObjectURL(this._localFileBlobs[f]))}}a.baseUrl?this._baseUrl=a.baseUrl:(f=location.origin,this._baseUrl=("null"===f?"file:///":f)+location.pathname,f=this._baseUrl.lastIndexOf("/"),-1!==f&&(this._baseUrl=this._baseUrl.substr(0,f+1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);
f=new MessageChannel;this._messageChannelPort=f.port1;this._messageChannelPort.onmessage=g=>this._OnMessageFromRuntime(g.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(g=>this._OnMessageFromDebugger(g));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this._useWorker?await this._InitWorker(a,f.port2):
await this._InitDOM(a,f.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?this._localFileBlobs[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async CreateWorker(a,f,g){if(a.startsWith("blob:"))return new Worker(a,g);if("cordova"===
this._exportType&&this._isFileProtocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(g.isC3MainWorker?a:this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),g);a=new URL(a,f);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),g)}return new Worker(a,g)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,
1)}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,isFullscreen:d.IsDocumentFullscreen(),projectData:a.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:-1<
self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:x,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isFileProtocol:this._isFileProtocol,isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,f){var g=this._GetWorkerURL(a.workerMainUrl);
this._worker=await this.CreateWorker(g,this._baseUrl,{type:"module",name:"Runtime",isC3MainWorker:!0});this._canvas=document.createElement("canvas");this._canvas.style.display="none";g=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;let k=a.workerDependencyScripts||[],p=a.engineScripts;k=await Promise.all(k.map(m=>this._MaybeGetCordovaScriptURL(m)));p=await Promise.all(p.map(m=>this._MaybeGetCordovaScriptURL(m)));if("cordova"===this._exportType)for(let m=
0,q=a.projectScripts.length;m<q;++m){const t=a.projectScripts[m],C=t[0];if(C===a.mainProjectScript||"scriptsInEvents.js"===C||C.endsWith("/scriptsInEvents.js"))t[1]=await this._MaybeGetCordovaScriptURL(C)}this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:f,canvas:g,workerDependencyScripts:k,engineScripts:p,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[f,
g,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=A.map(m=>new m(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(m,q)=>this._runtimeDomHandler._InvokeFunctionFromJS(m,q);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,f){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=
A.map(m=>new m(this));this._FindRuntimeDOMHandler();var g=a.engineScripts.map(m=>"string"===typeof m?(new URL(m,this._baseUrl)).toString():m);Array.isArray(a.workerDependencyScripts)&&g.unshift(...a.workerDependencyScripts);g=await Promise.all(g.map(m=>this._MaybeGetCordovaScriptURL(m)));await Promise.all(g.map(m=>l(m)));g=self.C3_ProjectScriptsStatus;const k=a.mainProjectScript,p=a.projectScripts;for(let [m,q]of p)if(q||(q=m),m===k)try{q=await this._MaybeGetCordovaScriptURL(q),await l(q),"preview"!==
this._exportType||g[m]||this._ReportProjectMainScriptError(m,"main script did not run to completion")}catch(t){this._ReportProjectMainScriptError(m,t)}else if("scriptsInEvents.js"===m||m.endsWith("/scriptsInEvents.js"))q=await this._MaybeGetCordovaScriptURL(q),await l(q);"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(a=Object.assign(this._GetCommonRuntimeOptions(a),{isInWorker:!1,messagePort:f,canvas:this._canvas,runOnStartupFunctions:B}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectMainScriptError(a,f){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,f);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,f,g,k,p){this._messageChannelPort.postMessage({type:"event",component:a,handler:f,dispatchOpts:k||null,data:g,responseId:null},p)}PostToRuntimeComponentAsync(a,
f,g,k,p){const m=F++,q=new Promise((t,C)=>{u.set(m,{resolve:t,reject:C})});this._messageChannelPort.postMessage({type:"event",component:a,handler:f,dispatchOpts:k||null,data:g,responseId:m},p);return q}["_OnMessageFromRuntime"](a){const f=a.type;if("event"===f)return this._OnEventFromRuntime(a);if("result"===f)this._OnResultFromRuntime(a);else if("runtime-ready"===f)this._OnRuntimeReady();else if("alert-error"===f)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===f)this._OnBeforeCreateRuntime();
else throw Error(`unknown message '${f}'`);}_OnEventFromRuntime(a){const f=a.component,g=a.handler,k=a.data,p=a.responseId;if(a=D.get(f))if(a=a.get(g)){var m=null;try{m=a(k)}catch(q){console.error(`Exception in '${f}' handler '${g}':`,q);null!==p&&this._PostResultToRuntime(p,!1,""+q);return}if(null===p)return m;m&&m.then?m.then(q=>this._PostResultToRuntime(p,!0,q)).catch(q=>{console.error(`Rejection from '${f}' handler '${g}':`,q);this._PostResultToRuntime(p,!1,""+q)}):this._PostResultToRuntime(p,
!0,m)}else console.warn(`[DOM] No handler '${g}' for component '${f}'`);else console.warn(`[DOM] No event handlers for component '${f}'`)}_PostResultToRuntime(a,f,g){let k;g&&g.transferables&&(k=g.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:f,result:g},k)}_OnResultFromRuntime(a){const f=a.responseId,g=a.isOk;a=a.result;const k=u.get(f);g?k.resolve(a):k.reject(a);u.delete(f)}AddRuntimeComponentMessageHandler(a,f,g){let k=D.get(a);k||(k=new Map,D.set(a,k));if(k.has(f))throw Error(`[DOM] Component '${a}' already has handler '${f}'`);
k.set(f,g)}static AddDOMHandlerClass(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||c)}static _SetWrapperIsFullscreenFlag(a){c=!!a}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&
this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!x[a]}async _WasmDecodeWebMOpus(a){a=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a){return"cordova"===this._exportType&&(a.startsWith("file:")||this._isFileProtocol&&this.IsRelativeURL(a))?(a.startsWith(this._baseUrl)&&(a=a.substr(this._baseUrl.length)),a=await this.CordovaFetchLocalFileAsArrayBuffer(a),
a=new Blob([a],{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const f=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(f);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(f);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,
f){a=a[f];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const f=this._GetPermissionAPI();return new Promise((g,k)=>f.checkPermission(this._MapPermissionID(f,a),p=>g(!!p.hasPermission),k))}_RequestPermission(a){const f=this._GetPermissionAPI();return new Promise((g,k)=>f.requestPermission(this._MapPermissionID(f,a),p=>g(!!p.hasPermission),k))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const f of a)if(!await this._HasPermission(f)&&
!1===await this._RequestPermission(f))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const f=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((g,k)=>{window.resolveLocalFileSystemURL(f,p=>{p.file(g,k)},k)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await H(a)}_CordovaMaybeStartNextArrayBufferRead(){if(y.length&&!(8<=z)){z++;
var a=y.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((f,g)=>{y.push({filename:a,successCallback:k=>{z--;this._CordovaMaybeStartNextArrayBufferRead();f(k)},errorCallback:k=>{z--;this._CordovaMaybeStartNextArrayBufferRead();g(k)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,f,g){try{const k=await this.CordovaFetchLocalFile(a),p=await E(k);
f(p)}catch(k){g(k)}}_SendWrapperMessage(a){if("windows-webview2"===this._exportType)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this._exportType)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async _ConvertDataUrisToBlobs(){const a=[];for(const [f,g]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(f,g));await Promise.all(a)}async _ConvertDataUriToBlobs(a,f){if("object"===
typeof f)this._localFileBlobs[a]=new Blob([f.str],{type:f.type}),this._localFileStrings[a]=f.str;else{let g=await this._FetchDataUri(f);g||(g=this._DataURIToBinaryBlobSync(f));this._localFileBlobs[a]=g}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(f){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",f),null}}_DataURIToBinaryBlobSync(a){a=
this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var f=a.indexOf(",");if(0>f)throw new URIError("expected comma in data: uri");var g=a.substring(5,f);a=a.substring(f+1);f=g.split(";");g=f[0]||"";const k=f[2];a="base64"===f[1]||"base64"===k?atob(a):decodeURIComponent(a);return{mime_type:g,data:a}}_BinaryStringToBlob(a,f){var g=a.length;let k=g>>2,p=new Uint8Array(g),m=new Uint32Array(p.buffer,0,k),q,t;for(t=q=0;q<k;++q)m[q]=a.charCodeAt(t++)|a.charCodeAt(t++)<<
8|a.charCodeAt(t++)<<16|a.charCodeAt(t++)<<24;for(g&=3;g--;)p[t]=a.charCodeAt(t),++t;return new Blob([p],{type:f})}}}"use strict";
{const b=self.RuntimeInterface;function e(c){return c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents}const h=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),l={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},n={dispatchUserScriptEvent:!0},r={dispatchRuntimeEvent:!0};function v(c){return new Promise((d,a)=>{const f=document.createElement("link");f.onload=()=>d(f);f.onerror=
g=>a(g);f.rel="stylesheet";f.href=c;document.head.appendChild(f)})}function w(c){return new Promise((d,a)=>{const f=new Image;f.onload=()=>d(f);f.onerror=g=>a(g);f.src=c})}async function x(c){c=URL.createObjectURL(c);try{return await w(c)}finally{URL.revokeObjectURL(c)}}function H(c){return new Promise((d,a)=>{let f=new FileReader;f.onload=g=>d(g.target.result);f.onerror=g=>a(g);f.readAsText(c)})}async function E(c,d,a){if(!/firefox/i.test(navigator.userAgent))return await x(c);var f=await H(c);f=
(new DOMParser).parseFromString(f,"image/svg+xml");const g=f.documentElement;if(g.hasAttribute("width")&&g.hasAttribute("height")){const k=g.getAttribute("width"),p=g.getAttribute("height");if(!k.includes("%")&&!p.includes("%"))return await x(c)}g.setAttribute("width",d+"px");g.setAttribute("height",a+"px");f=(new XMLSerializer).serializeToString(f);c=new Blob([f],{type:"image/svg+xml"});return await x(c)}function y(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);
return!1}const z=new Set(["input","textarea","datalist","select"]);function A(c){return z.has(c.tagName.toLowerCase())||y(c)}const D=new Set(["canvas","body","html"]);function u(c){const d=c.target.tagName.toLowerCase();D.has(d)&&c.preventDefault()}function F(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}self.C3_GetSvgImageSize=async function(c){c=await x(c);if(0<c.width&&0<c.height)return[c.width,c.height];{c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";
document.body.appendChild(c);const d=c.getBoundingClientRect();document.body.removeChild(c);return[d.width,d.height]}};self.C3_RasterSvgImageBlob=async function(c,d,a,f,g){c=await E(c,d,a);const k=document.createElement("canvas");k.width=f;k.height=g;k.getContext("2d").drawImage(c,0,0,d,a);return k};let B=!1;document.addEventListener("pause",()=>B=!0);document.addEventListener("resume",()=>B=!1);function I(){try{return window.parent&&window.parent.document.hasFocus()}catch(c){return!1}}function G(){const c=
document.activeElement;if(!c)return!1;const d=c.tagName.toLowerCase(),a=new Set("email number password search tel text url".split(" "));return"textarea"===d?!0:"input"===d?a.has(c.type.toLowerCase()||"text"):y(c)}b.AddDOMHandlerClass(class extends self.DOMHandler{constructor(c){super(c,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=
this._debugHighlightElem=null;this._pointerRawMovementY=this._pointerRawMovementX=0;this._lastWindowWidth=c._GetWindowInnerWidth();this._lastWindowHeight=c._GetWindowInnerHeight();this._virtualKeyboardHeight=0;c.AddRuntimeComponentMessageHandler("canvas","update-size",f=>this._OnUpdateCanvasSize(f));c.AddRuntimeComponentMessageHandler("runtime","invoke-download",f=>this._OnInvokeDownload(f));c.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",f=>this._OnRasterSvgImage(f));c.AddRuntimeComponentMessageHandler("runtime",
"get-svg-image-size",f=>this._OnGetSvgImageSize(f));c.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",f=>this._OnSetTargetOrientation(f));c.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());c.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",f=>this._OnPostToDebugger(f));c.AddRuntimeComponentMessageHandler("runtime","go-to-script",f=>this._OnPostToDebugger(f));c.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>
this._OnBeforeStartTicking());c.AddRuntimeComponentMessageHandler("runtime","debug-highlight",f=>this._OnDebugHighlight(f));c.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());c.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());c.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",f=>this._OnAddStylesheet(f));c.AddRuntimeComponentMessageHandler("runtime","alert",f=>this._OnAlert(f));
c.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const d=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",f=>{const g=f.target,k=g.tagName.toLowerCase();d.has(k)||y(g)||f.preventDefault()});const a=c.GetCanvas();window.addEventListener("selectstart",u);window.addEventListener("gesturehold",u);a.addEventListener("selectstart",u);a.addEventListener("gesturehold",u);window.addEventListener("touchstart",u,{passive:!1});
"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",u,{passive:!1}),a.addEventListener("pointerdown",u)):a.addEventListener("touchstart",u);this._mousePointerLastButtons=0;window.addEventListener("mousedown",f=>{1===f.button&&f.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());
window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",f=>this._OnFullscreenError(f));window.addEventListener("webkitfullscreenerror",f=>this._OnFullscreenError(f));window.addEventListener("mozfullscreenerror",f=>this._OnFullscreenError(f));c.IsiOSWebView()&&window.addEventListener("focusout",()=>{G()||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=
f=>this._OnWrapperMessage(f);this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!B)}}Attach(){window.addEventListener("focus",
()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:I()});this._mousePointerLastButtons=0});window.addEventListener("focusin",d=>{A(d.target)&&this._PostRuntimeEvent("keyboard-blur")});window.addEventListener("keydown",d=>this._OnKeyEvent("keydown",d));window.addEventListener("keyup",d=>this._OnKeyEvent("keyup",d));window.addEventListener("dblclick",d=>this._OnMouseEvent("dblclick",d,l));window.addEventListener("wheel",
d=>this._OnMouseWheelEvent("wheel",d));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",d=>{this._HandlePointerDownFocus(d);this._OnPointerEvent("pointerdown",d)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",d=>this._OnPointerRawUpdate(d))):
window.addEventListener("pointermove",d=>this._OnPointerEvent("pointermove",d)),window.addEventListener("pointerup",d=>this._OnPointerEvent("pointerup",d)),window.addEventListener("pointercancel",d=>this._OnPointerEvent("pointercancel",d))):(window.addEventListener("mousedown",d=>{this._HandlePointerDownFocus(d);this._OnMouseEventAsPointer("pointerdown",d)}),window.addEventListener("mousemove",d=>this._OnMouseEventAsPointer("pointermove",d)),window.addEventListener("mouseup",d=>this._OnMouseEventAsPointer("pointerup",
d)),window.addEventListener("touchstart",d=>{this._HandlePointerDownFocus(d);this._OnTouchEvent("pointerdown",d)}),window.addEventListener("touchmove",d=>this._OnTouchEvent("pointermove",d)),window.addEventListener("touchend",d=>this._OnTouchEvent("pointerup",d)),window.addEventListener("touchcancel",d=>this._OnTouchEvent("pointercancel",d)));const c=()=>this._PlayPendingMedia();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);
window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0);this._iRuntime.IsAndroid()&&!this._iRuntime.IsAndroidWebView()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this._OnAndroidVirtualKeyboardChange(this._GetWindowInnerHeight(),navigator.virtualKeyboard.boundingRect.height)}))}_OnAndroidVirtualKeyboardChange(c,d){document.body.style.transform="";if(0<d){var a=document.activeElement;
a&&(a=a.getBoundingClientRect(),c=(a.top+a.bottom)/2-(c-d)/2,c>d&&(c=d),0>c&&(c=0),0<c&&(document.body.style.transform=`translateY(${-c}px)`))}}_PostRuntimeEvent(c,d){this.PostToRuntime(c,d||null,r)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const c=this._GetWindowInnerWidth(),d=this._GetWindowInnerHeight();if(this._iRuntime.IsAndroidWebView()){if(this._lastWindowWidth===c&&d<this._lastWindowHeight){this._virtualKeyboardHeight=
this._lastWindowHeight-d;this._OnAndroidVirtualKeyboardChange(this._lastWindowHeight,this._virtualKeyboardHeight);return}0<this._virtualKeyboardHeight&&(this._virtualKeyboardHeight=0,this._OnAndroidVirtualKeyboardChange(d,this._virtualKeyboardHeight));this._lastWindowWidth=c;this._lastWindowHeight=d}this._PostRuntimeEvent("window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:b.IsDocumentFullscreen()});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&
clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(c,d,0))}_ScheduleSimulatedResize(c,d,a){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(c,d,a),48)}_OnSimulatedResize(c,d,a){const f=this._GetWindowInnerWidth(),g=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;f!=c||g!=d?this._PostRuntimeEvent("window-resize",{innerWidth:f,innerHeight:g,devicePixelRatio:window.devicePixelRatio,
isFullscreen:b.IsDocumentFullscreen()}):10>a&&this._ScheduleSimulatedResize(f,g,a+1)}_OnSetTargetOrientation(c){this._targetOrientation=c.targetOrientation}_TrySetTargetOrientation(){const c=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(d=>console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(c):screen.webkitLockOrientation?d=screen.webkitLockOrientation(c):screen.mozLockOrientation?
d=screen.mozLockOrientation(c):screen.msLockOrientation&&(d=screen.msLockOrientation(c));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",d)}}_OnFullscreenChange(){const c=b.IsDocumentFullscreen();c&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:c,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(c){console.warn("[Construct 3] Fullscreen request failed: ",
c);this.PostToRuntime("fullscreenerror",{isFullscreen:b.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(c){c?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:c})}_OnKeyEvent(c,d){"Backspace"===d.key&&u(d);const a=h.get(d.code)||d.code;this._PostToRuntimeMaybeSync(c,{code:a,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,
metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},l)}_OnMouseWheelEvent(c,d){this.PostToRuntime(c,{clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,deltaX:d.deltaX,deltaY:d.deltaY,deltaZ:d.deltaZ,deltaMode:d.deltaMode,timeStamp:d.timeStamp},l)}_OnMouseEvent(c,d,a){e(d)||this._PostToRuntimeMaybeSync(c,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,movementX:d.movementX||0,movementY:d.movementY||0,timeStamp:d.timeStamp},a)}_OnMouseEventAsPointer(c,
d){if(!e(d)){var a=this._mousePointerLastButtons;"pointerdown"===c&&0!==a?c="pointermove":"pointerup"===c&&0!==d.buttons&&(c="pointermove");this._PostToRuntimeMaybeSync(c,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:a,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,movementX:d.movementX||0,movementY:d.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},l);this._mousePointerLastButtons=d.buttons;
this._OnMouseEvent(d.type,d,n)}}_OnPointerEvent(c,d){this._pointerRawUpdateRateLimiter&&"pointermove"!==c&&this._pointerRawUpdateRateLimiter.Reset();var a=0;"mouse"===d.pointerType&&(a=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(c,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:a,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,movementX:(d.movementX||0)+this._pointerRawMovementX,movementY:(d.movementY||0)+this._pointerRawMovementY,
width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},l);this._pointerRawMovementY=this._pointerRawMovementX=0;"mouse"===d.pointerType&&(a="mousemove","pointerdown"===c?a="mousedown":"pointerup"===c&&(a="mouseup"),this._OnMouseEvent(a,d,n),this._mousePointerLastButtons=d.buttons)}_OnPointerRawUpdate(c){this._lastPointerRawUpdateEvent&&(this._pointerRawMovementX+=this._lastPointerRawUpdateEvent.movementX||
0,this._pointerRawMovementY+=this._lastPointerRawUpdateEvent.movementY||0);this._lastPointerRawUpdateEvent=c;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(c,d){for(let a=0,f=d.changedTouches.length;a<f;++a){const g=d.changedTouches[a];this._PostToRuntimeMaybeSync(c,{pointerId:g.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:g.clientX,
clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:d.movementX||0,movementY:d.movementY||0,width:2*(g.radiusX||g.webkitRadiusX||0),height:2*(g.radiusY||g.webkitRadiusY||0),pressure:g.force||g.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:g.rotationAngle||0,timeStamp:d.timeStamp},l)}}_HandlePointerDownFocus(c){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(c.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&document.activeElement.blur()}_IsElementCanvasOrDocument(c){return!c||
c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",c=>this._OnDeviceOrientation(c)),window.addEventListener("deviceorientationabsolute",c=>this._OnDeviceOrientationAbsolute(c)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",c=>this._OnDeviceMotion(c)))}_OnDeviceOrientation(c){this.PostToRuntime("deviceorientation",
{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp,webkitCompassHeading:c.webkitCompassHeading,webkitCompassAccuracy:c.webkitCompassAccuracy},l)}_OnDeviceOrientationAbsolute(c){this.PostToRuntime("deviceorientationabsolute",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp},l)}_OnDeviceMotion(c){let d=null;var a=c.acceleration;a&&(d={x:a.x||0,y:a.y||0,z:a.z||0});a=null;var f=c.accelerationIncludingGravity;f&&(a=
{x:f.x||0,y:f.y||0,z:f.z||0});f=null;const g=c.rotationRate;g&&(f={alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0});this.PostToRuntime("devicemotion",{acceleration:d,accelerationIncludingGravity:a,rotationRate:f,interval:c.interval,timeStamp:c.timeStamp},l)}_OnUpdateCanvasSize(c){const d=this.GetRuntimeInterface().GetCanvas();d.style.width=c.styleWidth+"px";d.style.height=c.styleHeight+"px";d.style.marginLeft=c.marginLeft+"px";d.style.marginTop=c.marginTop+"px";this._isFirstSizeUpdate&&(d.style.display=
"",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(c){const d=c.url;c=c.filename;const a=document.createElement("a"),f=document.body;a.textContent=c;a.href=d;a.download=c;f.appendChild(a);a.click();f.removeChild(a)}async _OnRasterSvgImage(c){var d=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);d=d?await createImageBitmap(c,d):await createImageBitmap(c);return{imageBitmap:d,transferables:[d]}}async _OnGetSvgImageSize(c){return await self.C3_GetSvgImageSize(c.blob)}async _OnAddStylesheet(c){await v(c.url)}_PlayPendingMedia(){var c=
[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const d of c)(c=d.play())&&c.catch(a=>{this._mediaRemovedPendingPlay.has(d)||this._mediaPendingPlay.add(d)})}TryPlayMedia(c){if("function"!==typeof c.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(c);let d;try{d=c.play()}catch(a){this._mediaPendingPlay.add(c);return}d&&d.catch(a=>{this._mediaRemovedPendingPlay.has(c)||this._mediaPendingPlay.add(c)})}RemovePendingPlay(c){this._mediaPendingPlay.delete(c);
this._mediaRemovedPendingPlay.add(c)}SetSilent(c){this._isSilent=!!c}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(c){if(c.show){this._debugHighlightElem||(this._debugHighlightElem=document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var d=this._debugHighlightElem;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=
c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}_InvokeFunctionFromJS(c,d){return this.PostToRuntimeAsync("js-invoke-function",{name:c,params:d})}_OnAlert(c){alert(c.message)}_OnWrapperMessage(c){"entered-fullscreen"===c?(b._SetWrapperIsFullscreenFlag(!0),
this._OnFullscreenChange()):"exited-fullscreen"===c?(b._SetWrapperIsFullscreenFlag(!1),this._OnFullscreenChange()):console.warn("Unknown wrapper message: ",c)}})}"use strict";
self.JobSchedulerDOM=class{constructor(b){this._runtimeInterface=b;this._baseUrl=b.GetBaseURL();"preview"===b.GetExportType()?this._baseUrl+="workers/":this._baseUrl+=b.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var b=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(b,this._baseUrl,{name:"DispatchWorker"});b=new MessageChannel;this._inputPort=b.port1;this._dispatchWorker.postMessage({type:"_init","in-port":b.port2},[b.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const b=this._jobWorkers.length;var e=this._runtimeInterface._GetWorkerURL("jobworker.js");e=await this._runtimeInterface.CreateWorker(e,this._baseUrl,{name:"JobWorker"+b});const h=new MessageChannel,l=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:h.port1},[h.port1]);e.postMessage({type:"init",number:b,"dispatch-port":h.port2,"output-port":l.port2},[h.port2,l.port2]);this._jobWorkers.push(e);return l.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!0,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
{function b(h){h.stopPropagation()}function e(h){13!==h.which&&27!==h.which&&h.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(h){super(h,"text-input");this.AddDOMElementMessageHandler("scroll-to-bottom",l=>this._OnScrollToBottom(l))}CreateElement(h,l){let n;const r=l.type;"textarea"===r?(n=document.createElement("textarea"),n.style.resize="none"):(n=document.createElement("input"),n.type=r);n.style.position="absolute";n.autocomplete="off";
n.addEventListener("touchstart",b);n.addEventListener("touchmove",b);n.addEventListener("touchend",b);n.addEventListener("mousedown",b);n.addEventListener("mouseup",b);n.addEventListener("keydown",e);n.addEventListener("keyup",e);n.addEventListener("click",v=>{v.stopPropagation();this._PostToRuntimeElementMaybeSync("click",h)});n.addEventListener("dblclick",v=>{v.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",h)});n.addEventListener("input",()=>this.PostToRuntimeElement("change",
h,{text:n.value}));l.id&&(n.id=l.id);this.UpdateState(n,l);return n}UpdateState(h,l){h.value=l.text;h.placeholder=l.placeholder;h.title=l.title;h.disabled=!l.isEnabled;h.readOnly=l.isReadOnly;h.spellcheck=l.spellCheck;l=l.maxLength;0>l?h.removeAttribute("maxlength"):h.setAttribute("maxlength",l)}_OnScrollToBottom(h){h.scrollTop=h.scrollHeight}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"touch");this.AddRuntimeMessageHandler("request-permission",e=>this._OnRequestPermission(e))}async _OnRequestPermission(b){b=b.type;let e=!0;0===b?e=await this._RequestOrientationPermission():1===b&&(e=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:b,result:e})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"mouse");this.AddRuntimeMessageHandlers([["cursor",e=>this._OnChangeCursorStyle(e)],["request-pointer-lock",()=>this._OnRequestPointerLock()],["release-pointer-lock",()=>this._OnReleasePointerLock()]]);document.addEventListener("pointerlockchange",e=>this._OnPointerLockChange());document.addEventListener("pointerlockerror",e=>this._OnPointerLockError())}_OnChangeCursorStyle(b){document.documentElement.style.cursor=
b}_OnRequestPointerLock(){this._iRuntime.GetCanvas().requestPointerLock()}_OnReleasePointerLock(){document.exitPointerLock()}_OnPointerLockChange(){this.PostToRuntime("pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})}_OnPointerLockError(){this.PostToRuntime("pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"platform-info");this.AddRuntimeMessageHandlers([["get-initial-state",()=>this._OnGetInitialState()],["request-wake-lock",()=>this._OnRequestWakeLock()],["release-wake-lock",()=>this._OnReleaseWakeLock()]]);window.addEventListener("resize",()=>this._OnResize());this._screenWakeLock=null}_OnGetInitialState(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:this._GetSafeAreaInset(),supportsWakeLock:!!navigator.wakeLock}}_GetSafeAreaInset(){var b=document.body;const e=b.style;e.setProperty("--temp-sai-top","env(safe-area-inset-top)");e.setProperty("--temp-sai-right","env(safe-area-inset-right)");e.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");e.setProperty("--temp-sai-left","env(safe-area-inset-left)");b=getComputedStyle(b);b=[b.getPropertyValue("--temp-sai-top"),b.getPropertyValue("--temp-sai-right"),b.getPropertyValue("--temp-sai-bottom"),
b.getPropertyValue("--temp-sai-left")].map(h=>{h=parseInt(h,10);return isFinite(h)?h:0});e.removeProperty("--temp-sai-top");e.removeProperty("--temp-sai-right");e.removeProperty("--temp-sai-bottom");e.removeProperty("--temp-sai-left");return b}_OnResize(){this.PostToRuntime("window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:this._GetSafeAreaInset()})}async _OnRequestWakeLock(){if(!this._screenWakeLock)try{this._screenWakeLock=await navigator.wakeLock.request("screen"),
this._screenWakeLock.addEventListener("release",()=>this._OnWakeLockReleased()),console.log("[Construct 3] Screen wake lock acquired"),this.PostToRuntime("wake-lock-acquired")}catch(b){console.warn("[Construct 3] Failed to acquire screen wake lock: ",b),this.PostToRuntime("wake-lock-error")}}_OnReleaseWakeLock(){this._screenWakeLock&&(this._screenWakeLock.release(),this._screenWakeLock=null)}_OnWakeLockReleased(){console.log("[Construct 3] Screen wake lock released");this._screenWakeLock=null;this.PostToRuntime("wake-lock-released")}});
"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"nwjs");this._isNWjs=!1;this.AddRuntimeMessageHandlers([["init",()=>this.Init()],["show-open-dlg",e=>this._OnShowOpenDlg(e)],["show-folder-dlg",()=>this._OnShowFolderDlg()],["show-save-dlg",e=>this._OnShowSaveDlg(e)],["set-title",e=>this._OnSetTitle(e)],["set-window-x",e=>this._OnSetWindowX(e)],["set-window-y",e=>this._OnSetWindowY(e)],["set-window-width",e=>this._OnSetWindowWidth(e)],["set-window-height",e=>
this._OnSetWindowHeight(e)],["window-cmd",e=>this._OnWindowCommand(e)],["window-attention",e=>this._OnWindowRequestAttention(e)],["set-window-max-size",e=>this._OnSetWindowMaxSize(e)],["set-window-min-size",e=>this._OnSetWindowMinSize(e)],["set-window-resizable",e=>this._OnSetWindowResizable(e)],["set-window-always-top",e=>this._OnSetWindowAlwaysOnTop(e)],["shell-cmd",e=>this._OnShellCommand(e)],["set-clipboard",e=>this._OnSetClipboard(e)],["clear-clipboard",()=>this._OnClearClipboard()]])}GetWindow(){return nw.Window.get()}_CreateNwjsInputElem(b,
e){const h=document.createElement("input");h.type="file";h.style.display="none";h.id=b;e&&h.setAttribute(e,"");document.body.appendChild(h);return h}Init(){this._isNWjs=!0;nw.App.clearCache();window.addEventListener("dragover",r=>r.preventDefault());window.addEventListener("drop",r=>this._OnDrop(r));const b=this._CreateNwjsInputElem("c3nwOpenFileDialog");b.onchange=r=>{this.PostToRuntime("open-dlg",{chosenPath:b.value});try{b.value=null}catch(v){}};b.oncancel=()=>{this.PostToRuntime("open-dlg-cancel")};
const e=this._CreateNwjsInputElem("c3nwChooseFolderDialog","nwdirectory");e.onchange=r=>{this.PostToRuntime("folder-dlg",{chosenPath:e.value});try{e.value=null}catch(v){}};e.oncancel=()=>{this.PostToRuntime("folder-dlg-cancel")};const h=this._CreateNwjsInputElem("c3nwSaveDialog","nwsaveas");h.onchange=r=>{this.PostToRuntime("save-dlg",{chosenPath:h.value});try{h.value=null}catch(v){}};h.oncancel=()=>{this.PostToRuntime("save-dlg-cancel")};const l=this.GetWindow();l.on("move",r=>this._OnWindowChange(r));
l.on("resize",r=>this._OnWindowChange(r));let n=this._GetClipboardText();setInterval(()=>{const r=this._GetClipboardText();n!==r&&(n=r,this.PostToRuntime("clipboard-change",{"clipboard-text":r}))},1E3);return Object.assign({argv:nw.App.argv,"clipboard-text":n},this._GetWindowInfo())}_GetWindowInfo(){const b=this.GetWindow();return{"window-title":b.title||"","window-x":b.x,"window-y":b.y,"window-width":b.width,"window-height":b.height}}_OnWindowChange(b){this.PostToRuntime("window-change",this._GetWindowInfo())}_GetClipboardText(){return nw.Clipboard.get().get()||
""}_OnClipboardChange(){this.PostToRuntime("clipboard-change",this._GetClipboardInfo())}_OnSetWindowX(b){this.GetWindow().x=b.x}_OnSetWindowY(b){this.GetWindow().y=b.y}_OnSetWindowWidth(b){const e=this.GetWindow();b=b.width;e.setInnerWidth?e.setInnerWidth(b):e.width=b}_OnSetWindowHeight(b){const e=this.GetWindow();b=b.height;e.setInnerHeight?e.setInnerHeight(b):e.height=b}_OnWindowCommand(b){const e=b.method;setTimeout(()=>this.GetWindow()[e](),100)}_OnWindowRequestAttention(b){this.GetWindow().requestAttention(b.request)}_OnSetWindowMaxSize(b){this.GetWindow().setMaximumSize(b.width,
b.height)}_OnSetWindowMinSize(b){this.GetWindow().setMinimumSize(b.width,b.height)}_OnSetWindowResizable(b){this.GetWindow().setResizable(b.resizable)}_OnSetWindowAlwaysOnTop(b){this.GetWindow().setAlwaysOnTop(b.top)}_OnShellCommand(b){nw.Shell[b.method](b.arg)}_OnSetClipboard(b){nw.Clipboard.get().set(b.text)}_OnClearClipboard(){nw.Clipboard.get().clear()}_OnDrop(b){b.preventDefault();b=b.dataTransfer.files;const e=[];for(let h=0,l=b.length;h<l;++h)e.push(b[h].path);this.PostToRuntime("drop",{filePaths:e});
return!1}_OnShowOpenDlg(b){if(this._isNWjs){var e=document.getElementById("c3nwOpenFileDialog");e.setAttribute("accept",b.accept);e.click()}}_OnShowFolderDlg(){this._isNWjs&&document.getElementById("c3nwChooseFolderDialog").click()}_OnShowSaveDlg(b){if(this._isNWjs){var e=document.getElementById("c3nwSaveDialog");e.setAttribute("accept",b.accept);e.click()}}_OnSetTitle(b){b=b.title;document.title=b;this.GetWindow().title=b}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"browser");this._exportType="";this.AddRuntimeMessageHandlers([["get-initial-state",e=>this._OnGetInitialState(e)],["ready-for-sw-messages",()=>this._OnReadyForSWMessages()],["alert",e=>this._OnAlert(e)],["close",()=>this._OnClose()],["set-focus",e=>this._OnSetFocus(e)],["vibrate",e=>this._OnVibrate(e)],["lock-orientation",e=>this._OnLockOrientation(e)],["unlock-orientation",()=>this._OnUnlockOrientation()],
["navigate",e=>this._OnNavigate(e)],["request-fullscreen",e=>this._OnRequestFullscreen(e)],["exit-fullscreen",()=>this._OnExitFullscreen()],["set-hash",e=>this._OnSetHash(e)]]);window.addEventListener("online",()=>this._OnOnlineStateChanged(!0));window.addEventListener("offline",()=>this._OnOnlineStateChanged(!1));window.addEventListener("hashchange",()=>this._OnHashChange());document.addEventListener("backbutton",()=>this._OnCordovaBackButton())}_OnGetInitialState(b){this._exportType=b.exportType;
return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}_OnReadyForSWMessages(){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(b=>this.PostToRuntime("sw-message",b.data))}_OnOnlineStateChanged(b){this.PostToRuntime("online-state",
{isOnline:b})}_OnCordovaBackButton(){this.PostToRuntime("backbutton")}GetNWjsWindow(){return"nwjs"===this._exportType?nw.Window.get():null}_OnAlert(b){alert(b.message)}_OnClose(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}_OnSetFocus(b){b=b.isFocus;if("nwjs"===this._exportType){const e=this.GetNWjsWindow();b?e.focus():e.blur()}else b?window.focus():window.blur()}_OnVibrate(b){navigator.vibrate&&
navigator.vibrate(b.pattern)}_OnLockOrientation(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(e=>console.warn("[Construct 3] Failed to lock orientation: ",e));else try{let e=!1;screen.lockOrientation?e=screen.lockOrientation(b):screen.webkitLockOrientation?e=screen.webkitLockOrientation(b):screen.mozLockOrientation?e=screen.mozLockOrientation(b):screen.msLockOrientation&&(e=screen.msLockOrientation(b));e||console.warn("[Construct 3] Failed to lock orientation")}catch(e){console.warn("[Construct 3] Failed to lock orientation: ",
e)}}_OnUnlockOrientation(){try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(b){}}_OnNavigate(b){var e=b.type;if("back"===e)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===e)window.history.forward();
else if("reload"===e)location.reload();else if("url"===e){e=b.url;const h=b.target;b=b.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(e,"_system"):"preview"===b||"windows-webview2"===b?window.open(e,"_blank"):this._isScirraArcade||(2===h?window.top.location=e:1===h?window.parent.location=e:window.location=e)}else"new-window"===e&&(e=b.url,b=b.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(e,"_system"):window.open(e,b))}_OnRequestFullscreen(b){if("windows-webview2"===
this._exportType||"macos-wkwebview"===this._exportType)self.RuntimeInterface._SetWrapperIsFullscreenFlag(!0),this._iRuntime._SendWrapperMessage({type:"set-fullscreen",fullscreen:!0});else{const e={navigationUI:"auto"};b=b.navUI;1===b?e.navigationUI="hide":2===b&&(e.navigationUI="show");b=document.documentElement;b.requestFullscreen?b.requestFullscreen(e):b.mozRequestFullScreen?b.mozRequestFullScreen(e):b.msRequestFullscreen?b.msRequestFullscreen(e):b.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?
b.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):b.webkitRequestFullScreen())}}_OnExitFullscreen(){"windows-webview2"===this._exportType||"macos-wkwebview"===this._exportType?(self.RuntimeInterface._SetWrapperIsFullscreenFlag(!1),this._iRuntime._SendWrapperMessage({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&
document.webkitCancelFullScreen()}_OnSetHash(b){location.hash=b.hash}_OnHashChange(){this.PostToRuntime("hashchange",{location:location.toString()})}});
